# Generated by Django 4.1 on 2024-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=50)),
                ('Other', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=1000)),
                ('Info', models.CharField(max_length=500)),
                ('Num', models.IntegerField(max_length=10)),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
