# Generated by Django 4.1 on 2024-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='found',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=50)),
                ('Other', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=1000)),
                ('Num', models.IntegerField(max_length=10)),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
