# Generated by Django 4.1 on 2024-01-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_alter_found_num_alter_lost_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='found',
        ),
        migrations.DeleteModel(
            name='lost',
        ),
    ]
