# Generated by Django 4.1 on 2024-01-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lost',
        ),
    ]
