# Generated by Django 4.1 on 2024-01-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0011_lost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lost',
        ),
    ]
