# Generated by Django 4.1 on 2024-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=250)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='lost',
            name='Image',
            field=models.ImageField(default=None, upload_to='\x0ciles'),
        ),
    ]
