# Generated by Django 4.1 on 2024-01-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_contacts_alter_lost_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
    ]
